### PR TITLE
Remove deprecated reason-react ReasonReact.Callback.t

### PR DESCRIPTION
**Pull request by wegry**
Reason React 0.4.1 added deprecation warnings for ReasonReact.Callback.t. This PR used regex replacement to swap

`ReasonReact.Callback.t\(([^)]*)\)`
for
`$1 => unit`

### CODE REVIEW

**Comment by Madsn** [comment]
Any chance of this getting merged @InsidersByte ?

**Comment by luciusmagn** [comment]
+1

**Comment by henry-hz** [comment]
+1

**Comment by guidorice** [comment]
It looks like it's moved from deprecated to removed in reason-react 0.6.0

 $ yarn build
>  The module or file ReasonReact.Callback can't be found.

**Pull request closed without merging**
