### PR TITLE
Add onClick to Card

### PR DESCRIPTION
**Pull request by guilhermedecampo**
Hey guys,

This PR adds onClick prop to Card.

Thank you.

### CODE REVIEW

**Comment by guilhermedecampo** [comment]
@InsidersByte any news on this 😞 ?

**Comment by InsidersByte** [comment]
Hey @guilhermedecampo 

Thanks for the contribution!

Sorry for the delay, I am on holiday in South America and have been for the past couple of weeks.

I'm back next week so will merge this pr and cut a release after i get back.

**Comment by guilhermedecampo** [comment]
Hey @InsidersByte if you are near `São Paulo - Brazil` let's drink some beers! 🍻 
Thank you for the effort on doing this bindings ;)

**Review by InsidersByte — APPROVED** [review]

**Comment by InsidersByte** [comment]
@guilhermedecampo I was in Rio, so that was pretty near, considering the size of the continent!

I have merged this and released this in v0.3.1

**Comment by guilhermedecampo** [comment]
Hope you had a great time!
Thanks,

**Pull request merged**
